// Renders the pixel-art portrait the hero's "edm." morphs into, from public/images/emanuele.jpg.
// Run after changing the photo: npm run portrait (writes src/app/pixel-field/portrait.ts).
import { readFileSync, writeFileSync } from 'node:fs';
import { chromium } from 'playwright';
import { PORTRAIT_SIZE, portraitString } from './portrait-lib.mjs';

// head and shoulders, in pixels of the 512px photo
const CROP = { x: 86, y: 72, size: 340 };

const photo = `data:image/jpeg;base64,${readFileSync('public/images/emanuele.jpg').toString('base64')}`;
const browser = await chromium.launch();
const page = await browser.newPage();
const rgba = await page.evaluate(
  async ({ photo, crop, size }) => {
    const img = new globalThis.Image();
    img.src = photo;
    await img.decode();
    const canvas = globalThis.document.createElement('canvas');
    canvas.width = size;
    canvas.height = size;
    const ctx = canvas.getContext('2d');
    ctx.imageSmoothingQuality = 'high';
    ctx.drawImage(img, crop.x, crop.y, crop.size, crop.size, 0, 0, size, size);
    return Array.from(ctx.getImageData(0, 0, size, size).data);
  },
  { photo, crop: CROP, size: PORTRAIT_SIZE },
);
await browser.close();

const cells = portraitString(rgba);
writeFileSync(
  'src/app/pixel-field/portrait.ts',
  `// Generated by scripts/portrait.mjs from public/images/emanuele.jpg: do not edit by hand.
/** ${String(PORTRAIT_SIZE)}×${String(PORTRAIT_SIZE)} palette slots, row by row: 0 empty, 1–2 dark, 3–5 skin. */
export const PORTRAIT = {
  size: ${String(PORTRAIT_SIZE)},
  cells: '${cells}',
} as const;
`,
);
for (let r = 0; r < PORTRAIT_SIZE; r++) console.log(cells.slice(r * PORTRAIT_SIZE, (r + 1) * PORTRAIT_SIZE).replace(/0/g, ' '));
