// Which of the repositories the content links are public (issue #81). GitHub answers 404 to a visitor for a private
// one, so the site links only the ones that answer 200 here: making a repository public (or private again) needs no
// edit, only a build (.github/workflows/repos.yml starts one when the answer changes).
// Writes src/app/content/public-repos.generated.ts (git-ignored); `--print` only prints the list, as JSON.
import { readFile, writeFile } from 'node:fs/promises';
import { setTimeout as sleep } from 'node:timers/promises';
import { pathToFileURL } from 'node:url';

export const OUT = 'src/app/content/public-repos.generated.ts';
const SOURCES = ['src/app/content/content.en.ts', 'src/app/content/content.it.ts'];
const REPO = /https:\/\/github\.com\/xdelmo\/[\w.-]+/g;

/** Every repository URL in the given sources, once each, sorted. */
export function repoUrls(texts) {
  return [...new Set(texts.flatMap((t) => t.match(REPO) ?? []))].sort();
}

export function moduleSource(urls) {
  return `// Generated by scripts/public-repos.mjs: the repositories that answer 200 to a visitor. Do not edit.\nexport const PUBLIC_REPOS: readonly string[] = ${JSON.stringify(urls, null, 2)};\n`;
}

/** 200 is public; 404 private (or gone); anything else is not an answer, and is retried. */
export async function isPublic(url, fetchImpl = globalThis.fetch, tries = 3) {
  for (let i = 1; ; i++) {
    try {
      const res = await fetchImpl(url, { method: 'HEAD', redirect: 'follow' });
      if (res.status === 200) return true;
      if (res.status === 404) return false;
      throw new Error(`HTTP ${String(res.status)}`);
    } catch (error) {
      if (i >= tries) throw new Error(`${url}: ${error instanceof Error ? error.message : String(error)}`, { cause: error });
      await sleep(1000 * i);
    }
  }
}

export async function publicRepos(urls, fetchImpl = globalThis.fetch) {
  const answers = await Promise.all(urls.map((url) => isPublic(url, fetchImpl)));
  return urls.filter((_, i) => answers[i]);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const urls = repoUrls(await Promise.all(SOURCES.map((f) => readFile(f, 'utf8'))));
  let found;
  try {
    found = await publicRepos(urls);
  } catch (error) {
    // a deploy must not guess: it could link a private repository, or drop public ones
    if (process.env['CI'] || process.env['NETLIFY']) {
      console.error(`public-repos: GitHub did not answer, stopping (${error.message})`);
      process.exit(1);
    }
    console.warn(`public-repos: GitHub did not answer, keeping the last list (${error.message})`);
    const kept = await readFile(OUT, 'utf8').catch(() => moduleSource([]));
    await writeFile(OUT, kept);
    process.exit(0);
  }
  if (process.argv.includes('--print')) {
    console.log(JSON.stringify(found));
  } else {
    const next = moduleSource(found);
    // unchanged file, untouched: a dev server would rebuild on every write
    if ((await readFile(OUT, 'utf8').catch(() => '')) !== next) await writeFile(OUT, next);
    console.log(`public-repos: ${String(found.length)} of ${String(urls.length)} linked repositories are public`);
  }
}
